### ISSUE TITLE
windows zip file includes MACOSX dir

### ISSUE THREAD

**Issue by lgiuliano** [Juniper/amt-vlc#3]
When unzipping the win zip file
(https://github.com/Juniper/amt-vlc/blob/master/precompiled-binaries/Windows/vlc-4.0.0-dev-win32.zip), there is an extra dir called MACOSX.  The dir only contaings one dll file.  

This appears to just be a harmless cosmetic issue.

**Comment by natzberg** [comment]
I repushed this but did it on my Mac, so if you can test this one more time I'll know whether to do it on my Windows laptop or not!

**Comment by lgiuliano** [comment]
I no longer see it, so looks good.  Closing
